server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: kr.co.bpservice.config.CamelCaseToSnakeAndUpperCaseStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true



  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://15.164.73.251:3306/S08P12D104?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: ssafy123
